.TH SAMTOOLS.PL "1" "December 2015" "samtools.pl 1.2" "User Commands"
.SH NAME
samtools.pl \- helper script for SAMtools
.SH SYNOPSIS
.B samtools.pl
\fI\,<command> \/\fR[\fI\,<arguments>\/\fR]
.SH DESCRIPTION
helper script for SAMtools
.TP
Command:
varFilter     filtering SNPs and short indels
.IP
pileup2fq     generate fastq from `pileup \fB\-c\fR'
.IP
showALEN      print alignment length (ALEN) following CIGAR
.SH AUTHOR
THe software was written by Heng Li <lh3@sanger.ac.uk>
.P
This manpage was written by Andreas Tille for the Debian distribution and can be used for any other usage of the program.
